name: 测试action机制
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - develop
      - feature/qq/*
      - releases/qq/*

jobs:
  build:
    # 作业名称为 Greeting
    name: 运行fef
    # 此作业在 Linux 上运行
    runs-on: ubuntu-latest
    steps:
      - name: 测试程序
        uses: blurooo/fef@master
        with:
          run: 'py-echo'
          params: 'hello, world'
        id: hello
      - name: 测试程序
        uses: blurooo/fef@master
        with:
          run: 'code-style'
          params: '-f'
          failedWhenNonZeroExit: true
        id: code-style
      # 此步骤打印上一步操作的输出（时间）。
      - name: 打印输出
        run: 'echo code ${{ steps.hello.outputs.code }}'