name: 测试action机制
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master

jobs:
  build:
    name: 测试action/fef
    runs-on: ubuntu-latest
    steps:
      - name: hello
        uses: blurooo/fef@master
        with:
          # 使用feflow工具py-echo打印hello, world
          run: 'py-echo'
          params: 'hello, world'
      - name: 代码规范检查
        uses: blurooo/fef@master
        with:
          # 使用feflow工具code-style扫描代码规范
          run: 'code-style'
          # 存在代码规范问题时中断流水线
          failedWhenNonZeroExit: true
